version: 2.1

jobs:
  serverless-helloword:
    docker:
      - image: nikolaik/python-nodejs:python3.8-nodejs14-alpine
    parameters:
      stage_name:
        type: string
    steps:
      - checkout

      - run:
          name: Check Pull Request
          command: |
            if [[ ! -z "$CIRCLE_PULL_REQUEST" ]]; then
              # parse pr# from URL https://github.com/fwang/sls-monorepo-with-circleci/pull/1
              PR_NUMBER=${CIRCLE_PULL_REQUEST##*/}
              echo "export PR_NUMBER=$PR_NUMBER" >> $BASH_ENV
              echo "Pull request #$PR_NUMBER";
            fi
      - run:
          name: Merge Pull Request
          command:
            if [[ ! -z "$PR_NUMBER" ]]; then
              git fetch origin +refs/pull/$PR_NUMBER/merge
              git checkout -qf FETCH_HEAD;
            fi
      - run:
          name: Install Serverless CLI
          command: npm i -g serverless

      - run:
          name: Install dependencies
          command: |
            npm install
            pip3 install -r requirements_test.txt

      - run:
          name: Running tests!
          command: npm test

      - run:
          name: Deploying serverless app in aws
#          command: sls deploy -s << parameters.stage_name >>
          command: |
            if [[ ! -z "$PR_NUMBER" ]]; then
              serverless deploy -s <<parameters.stage_name>>-$PR_NUMBER
            else
              echo "no deployment yet";
            fi

workflows:
  build-deploy:
    jobs:
      - serverless-helloword:
          name: Build & Deploy serverless helloworld
          stage_name: ${CIRCLE_BRANCH}
          context: serverless

