version: 2.1

jobs:
  build-service:
    docker:
      - image: nikolaik/python-nodejs:python3.8-nodejs14-alpine
    parameters:
      stage_name:
        type: string
    steps:
      - checkout
      - run:
          name: Install Serverless CLI
          command: |
            pwd
            ls -la
            npm i -g serverless
      - run:
          name: Install dependencies
          command: |
            npm install
            pip3 install -r requirements_test.txt
      - run:
          name: Running tests!
          command: npm test
      - run:
          name: Deploying serverless app in aws
          command: sls deploy --stage << parameters.stage_name >>

  remove-stage-service:
    docker:
      - image: nikolaik/python-nodejs:python3.8-nodejs14-alpine
    parameters:
      stage_name:
        type: string
    steps:
      - checkout
      - run:
          name: Install Serverless CLI
          command: npm i -g serverless
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Remove serverless app in aws
          command: |
            echo "<< parameters.stage_name >>"
            sls remove --stage << parameters.stage_name >>

workflows:
  build-deploy:
    jobs:
      - build-service:
          name: Build & Deploy serverless helloworld
          stage_name: ${CIRCLE_BRANCH}
          context: serverless
      - remove-stage-service:
          name: Remove serverless app
          stage_name: ${CIRCLE_TAG:9}
          context: serverless
          filters:
            tags:
              only: /^rm-stage-.*/
            branches:
              ignore: /.*/


